stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps: 
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim
  
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/interim/train_processed.csv
      - params.yaml
    params:
      - feature_engineering.max_features
      - feature_engineering.ngram_range
    outs:
      - data/processed/X_train_BOW.pkl
      - data/processed/y_train.pkl
      - data/processed/bow_vectorizer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/X_train_BOW.pkl
      - data/processed/y_train.pkl
      - data/processed/bow_vectorizer.pkl
      - params.yaml
    params:
      - model_building.lgbm_params
    outs:
      - models/lgbm_Youtube_sentiment.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - models/lgbm_Youtube_sentiment.pkl
      - data/processed/bow_vectorizer.pkl
      - data/interim/test_processed.csv
      - params.yaml
    outs:
      - reports/classification_report.json
      - reports/confusion_matrix_test_set.png
      - experiment_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - experiment_info.json
    outs: []

  
